# Generated by Django 5.2.13 on 2026-07-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('order_type', models.CharField(choices=[('GEOTERMALNI', 'Geotermální vrt'), ('VRTANA_STUDNA', 'Vrtaná studna'), ('OBOJI', 'Geotermální vrt i studna')], default='VRTANA_STUDNA', max_length=20)),
                ('order_state', models.CharField(choices=[('POPTAVKA', 'Poptávka (čeká se na cenovou nabídku)'), ('REALIZACE', 'Realizace (nájezd techniky)'), ('HYDRO_POSOUZENI', 'Získávání dat od hydrogeologa'), ('PREDANO', 'Předáno investorovi')], default='POPTAVKA', max_length=20)),
                ('customer_interest', models.CharField(choices=[('CEKA_SE', 'Čeká se na vyjádření'), ('MAM_ZAJEM', 'Mám zájem'), ('NEMAM_ZAJEM', 'Nemám zájem')], default='CEKA_SE', max_length=20)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, max_length=12)),
                ('warranty_from', models.DateField(blank=True, null=True)),
                ('warranty_to', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
