# Generated by Django 5.2

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filled_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "depth_meters",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "technical_specifications",
                    models.TextField(help_text="Specifická data o vrtu"),
                ),
                (
                    "alert_driller",
                    models.BooleanField(
                        default=True,
                        help_text="Upozorňovat vrtmistra na vyplnění",
                    ),
                ),
                (
                    "driller",
                    models.ForeignKey(
                        help_text="Vrtmistr, který zprávu vyplnil",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_reports",
                        to="projects.order",
                    ),
                ),
            ],
        ),
    ]
