# Generated by Django 5.2.13 on 2026-09-08 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_technicalreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrillingRig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='project_docs/')),
                ('document_type', models.CharField(choices=[('POVOLENI_Z_URADU', 'Povolení z úřadu'), ('PROJEKTOVA_DOKUMENTACE', 'Projektová dokumentace'), ('SMLOUVA', 'Smlouva'), ('JINE', 'Ostatní dokumentace')], max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.order')),
            ],
        ),
        migrations.CreateModel(
            name='DrillingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_contracted', models.BooleanField(default=False, help_text='True = Zasmluvněno natvrdo, neposouvat automaticky')),
                ('drilling_rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.drillingrig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.order')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Formát RRRR-MM (např. 2026-06)', max_length=7)),
                ('invoiced_amount', models.DecimalField(decimal_places=2, help_text='Kolik se za tento měsíc vyfakturovalo', max_digits=12)),
                ('is_sent', models.BooleanField(default=False, help_text='Zda sekretářka odeslala protokol objednateli')),
                ('admin_signature_hash', models.CharField(blank=True, help_text='Otisk elektronického podpisu admina', max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_protocols', to='projects.order')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.order')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='projects.order')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_photos/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS šířka pro zobrazení na mapě', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS délka pro zobrazení na mapě', max_digits=11, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.photogallery')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('INVESTOR', 'Investor'), ('STAVBYVEDOUCI', 'Stavbyvedoucí')], max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contacts', to='projects.order')),
            ],
        ),
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retention_type', models.CharField(choices=[('PO_PREDANI_DILA', 'Po předání díla'), ('PO_UPLYNUTI_ZARUKY', 'Po uplynutí záruky'), ('ZARIZENI_STAVENISTE', 'Zařízení staveniště')], max_length=30)),
                ('release_date', models.DateField(help_text='Předpokládané nebo smluvní datum uvolnění')),
                ('is_released', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retentions', to='projects.order')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_at', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('has_project_documentation', models.BooleanField(default=False, help_text='Zda má zákazník projektovou dokumentaci')),
                ('assigned_user', models.ForeignKey(help_text='Uživatel, který má místo navštívit', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='projects.order')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuttings_disposal', models.CharField(choices=[('V_MISTE', 'Likvidace v místě'), ('ODVOZ_KONTEJNEREM', 'Odvoz kontejnerem')], max_length=20)),
                ('has_electricity_25a', models.BooleanField(default=False, help_text='Možnost připojení k el. síti min 25 A')),
                ('has_water_connection', models.BooleanField(default=False, help_text='Připojení k vodě')),
                ('general_note', models.TextField(blank=True, help_text='Poznámka pro všechny', null=True)),
                ('site_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='projects.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='WellWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Číslo kroku 1 až 9')),
                ('status', models.CharField(choices=[('NEZAHAJENO', 'Nezahájeno'), ('PROBIHA', 'Probíhá'), ('SPLNENO', 'Splněno')], default='NEZAHAJENO', max_length=20)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('hydrogeologist', models.ForeignKey(blank=True, help_text='Přiřazený hydrogeolog', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='projects.order')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('project', 'step_number')},
            },
        ),
    ]
