from projects.views.base_create_api_view import BaseCreateAPIView
from projects.serializers.technical_report_serializer import TechnicalReportSerializer

class CreateTechnicalReportAPIView(BaseCreateAPIView):
    serializer_class=TechnicalReportSerializer