name: vrttech-prod

services:
  web:
    container_name: vrttech_web
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
              daphne -b 0.0.0.0 -p 8000 core.asgi:application"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
      - proxy-net

  client:
    container_name: vrttech_client
    build:
      context: ../client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - web
    networks:
      - app-network
      - proxy-net

  db:
    image: postgres:18.3-alpine
    container_name: vrttech_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: vrttech_redis
    restart: always
    expose:
      - "6379"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  proxy-net:
    external: true