from projects.views.base_create_api_view import BaseCreateAPIView
from projects.serializers.inspection_protocol_serializer import InspectionProtocolSerializer

class CreateProtocolAPIView(BaseCreateAPIView):
    serializer_class = InspectionProtocolSerializer
